program=helloworld


help:
	echo "Run $(program) for all languages run: make run_all"


build_hello:
	cd java; javac Helloworld.java
	cd csharp; mcs Helloworld.cs


run_all:
# Ada
	cd ada;\
	time(ezc $(program).adb)
# ASM
	cd assembly;\
	time(ezc $(program).s)
# Awk
	cd awk;\
	time(ezc $(program).awk)
# Batch - no
# C
	cd c;\
	time(ezc $(program).c)
# C#
	cd csharp/$(program);\
	time(ezc $(program).cs)
# C++
	cd cplusplus;\
	time(ezc $(program).cpp)
# Clojure
	cd clojure;\
	time(ezc $(program).clj)
# COBOL
	cd cobol;\
	time(ezc $(program).cob)
# Common Lisp
	cd commonlisp;\
	time(ezc $(program).lisp)
# Crystal
	cd crystal;\
	time(ezc $(program).cr)
# D
	cd d;\
	time(ezc $(program).d)
# Dart
	cd dart;\
	time(ezc $(program).dart)
# Elixir
#	cd elixir;\
#	time(ezc $(program).ex)
# Erlang
#	cd erlang;\
#	time(ezc $(program).erl)
# F#
	cd fsharp;\
	time(ezc $(program).fs)
# Fortran
	cd fortran;\
	time(ezc $(program).f95)
# GNUPlot
	cd gnuplot;\
	time(ezc $(program).plt)
# Go
	cd go;\
	time(ezc $(program).go)
# Groovy
	cd groovy;\
	time(ezc $(program).groovy)
# Haskell
	cd haskell;\
	time(ezc $(program).hs)
# Haxe - no
# HTML - no
# Java
#	cd java;\
#	time(ezc $(program).java)
# JavaScript
	cd javascript;\
	time(ezc $(program).js)
# Julia
	cd julia;\
	time(ezc $(program).jl)
# Kotlin
	cd kotlin;\
	time(ezc $(program).kt)
# Lua
	cd lua;\
	time(ezc $(program).lua)
# Nim
	cd nim;\
	time(ezc $(program).nim)
# Objective-C
	cd objective-c;\
	time(ezc $(program).m)
# Ocaml
	cd ocaml;\
	time(ezc $(program).ml)
# Octave
	cd octave;\
	time(ezc $(program).octave)
# OpenGL - no
# Pascal
	cd pascal;\
	time(ezc $(program).pas)
# Perl
	cd perl;\
	time(ezc $(program).perl)
# PHP
	cd php;\
	time(ezc $(program).php)
# PICOLisp
	cd picolisp;\
	time(ezc $(program).l)
# PowerShell
	cd powershell;\
	time(ezc $(program).ps1)
# Prolog
	cd prolog;\
	time(ezc $(program).pl)
# Python
	cd python;\
	time(ezc $(program).py)
# R
	cd r;\
	time(ezc $(program).r)
# Racket
	cd racket;\
	time(ezc $(program).rkt)
# Ruby
	cd ruby;\
	time(ezc $(program).rb)
# Rust
	cd rust;\
	time(ezc $(program).rs)
# Scala
	cd scala;\
	time(ezc $(program).scala)
# Scheme
	cd scheme;\
	time(ezc $(program).scm)
# Shell
	cd shell;\
	time(ezc $(program).sh)
# Smalltalk
	cd smalltalk;\
	time(ezc $(program).st)
# Standard ML
	cd standardml;\
	time(ezc $(program).sml)
# Swift
	cd swift;\
	time(ezc $(program).swift)
# Tcl
	cd tcl;\
	time(ezc $(program).tcl)
# TypeScript
	cd typescript;\
	time(ezc $(program).ts)
# V
	cd v;\
	time(ezc $(program).v)
# VimScript
#	cd vim;\
#	time(ezc $(program).vim)
# Visual Basic
	cd visualbasic;\
	time(ezc $(program).vb)
# WebAssembly
#	cd webassembly;\
#	time(ezc $(program).wat)
