# Download image
# $ docker pull node:latest
# or
# $ docker pull node:lts
FROM node:latest
LABEL maintainer="Thom Bakker <A1r@Pun.com>"
LABEL description="An example Dockerfile"

# Example run command
RUN ps aux

# List all images
# $ docker images -a

# List running containers
# $ docker ps -a

# Execute a command inside the container (ex: bash)
# $ docker exec -it <container name or id> bash
