# Download image
# $ docker pull node:latest
# or
# $ docker pull node:lts
FROM node:latest
MAINTAINER Thom Bakker <A1r@Pun.com>

# Example run command
RUN ps aux

# List all images
# $ docker images -a

# List running containers
# $ docker ps -a

# Execute a command inside the container (ex: bash)
# $ docker exec -it <container name or id> bash
